import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../styles/globals.css';

const interFont = localFont({
  src: '../../public/fonts/inter-var-latin.woff2',
  variable: '--font-inter',
});



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
